// Chemistry (Grade 11) syllabus — 2076 BS (Che. 201)
const chemistrySyllabus = {
  subject: 'chemistry',
  title: 'Chemistry Grade 11 Syllabus',
  code: 'Che. 201',
  areas: [
    {
      area: 'General and Physical Chemistry',
      totalHours: 46,
      units: [
        {
          unitNumber: 1,
          unitTitle: 'Foundation and Fundamentals',
          teachingHours: 2,
          topics: [
            'General introduction of chemistry',
            'Importance and scope of chemistry',
            'Basic concepts of chemistry (atoms, molecules, relative masses of atoms and molecules, atomic mass unit (amu), radicals, molecular formula, empirical formula)',
            'Percentage composition from molecular formula',
          ],
        },
        {
          unitNumber: 2,
          unitTitle: 'Stoichiometry',
          teachingHours: 8,
          topics: [
            "Dalton's atomic theory and its postulates",
            'Laws of stoichiometry',
            "Avogadro's law and deductions (Molecular mass vs vapour density, molecular mass vs volume of gas, molecular mass vs number of particles)",
            'Mole and its relation with mass, volume, and number of particles',
            'Calculations based on mole concept',
            'Limiting reactant and excess reactant',
            'Theoretical yield, experimental yield, and percentage yield',
            'Calculation of empirical and molecular formula from percentage composition (numerical problems)',
          ],
        },
        {
          unitNumber: 3,
          unitTitle: 'Atomic Structure',
          teachingHours: 8,
          topics: [
            "Rutherford's atomic model and its limitations",
            "Postulates of Bohr's atomic model and its applications",
            'Spectrum of hydrogen atom',
            "Defects of Bohr's theory",
            "Elementary idea of quantum mechanical model: de Broglie's wave equation",
            "Heisenberg's Uncertainty Principle",
            'Concept of probability',
            'Quantum Numbers',
            'Orbitals and shape of s and p orbitals only',
            'Aufbau Principle',
            "Pauli's exclusion principle",
            "Hund's rule and electronic configurations of atoms and ions (up to atomic no. 30)",
          ],
        },
        {
          unitNumber: 4,
          unitTitle: 'Classification of Elements and Periodic Table',
          teachingHours: 5,
          topics: [
            'Modern periodic law and modern periodic table (Classification of elements into groups, periods, and blocks)',
            'IUPAC classification of elements',
            'Nuclear charge and effective nuclear charge',
            'Periodic trend and periodicity (Atomic radii, ionic radii, ionization energy, electron affinity, electronegativity, metallic characters)',
          ],
        },
        {
          unitNumber: 5,
          unitTitle: 'Chemical Bonding and Shapes of Molecules',
          teachingHours: 9,
          topics: [
            'Valence shell, valence electron, and octet theory',
            'Ionic bond and its properties',
            'Covalent bond and coordinate covalent bond (Properties of covalent compounds)',
            'Lewis dot structure of some common compounds of s and p block elements',
            'Resonance',
            'VSEPR theory and shapes of simple molecules (BeF2, BF3, CH4, CH3Cl, PCl5, SF6, H2O, NH3, CO2, H2S, PH3)',
            'Elementary idea of Valence Bond Theory',
            'Hybridization involving s and p orbitals only',
            'Bond characteristics (Bond length, ionic character, dipole moment)',
            'Van der Waals force and molecular solids',
            'Hydrogen bonding and its applications',
            'Metallic bonding and properties of metallic solids',
          ],
        },
        {
          unitNumber: 6,
          unitTitle: 'Oxidation and Reduction',
          teachingHours: 5,
          topics: [
            'General and electronic concept of oxidation and reduction',
            'Oxidation number and rules for assigning oxidation number',
            'Balancing redox reactions by oxidation number and ion-electron (half reaction) method',
            "Electrolysis (Qualitative aspect & Quantitative aspect via Faraday's laws of electrolysis)",
          ],
        },
        {
          unitNumber: 7,
          unitTitle: 'States of Matter',
          teachingHours: 8,
          topics: [
            'Gaseous State: Kinetic theory of gas and its postulates',
            'Gaseous State: Gas laws (Boyle\'s law, Charles\' law, Avogadro\'s law, combined gas equation, Dalton\'s law of partial pressure, Graham\'s law of diffusion)',
            'Gaseous State: Ideal gas and ideal gas equation',
            'Gaseous State: Universal gas constant and its significance',
            'Gaseous State: Deviation of real gas from ideality',
            'Gaseous State: Numerical problems based on gas laws',
            'Liquid State: Physical properties of liquids (Evaporation, condensation, vapour pressure, boiling point, surface tension, viscosity)',
            'Liquid State: Liquid crystals and their applications',
            'Solid State: Types of solids (Amorphous and crystalline solids)',
            'Solid State: Efflorescent, Deliquescent, and Hygroscopic solids',
            'Solid State: Crystallization and crystal growth',
            'Solid State: Water of crystallization',
            'Solid State: Introduction to crystal lattice and unit cell',
          ],
        },
        {
          unitNumber: 8,
          unitTitle: 'Chemical Equilibrium',
          teachingHours: 3,
          topics: [
            'Physical and chemical equilibrium',
            'Dynamic nature of chemical equilibrium',
            'Law of mass action',
            'Expression for equilibrium constant and its importance',
            'Relationship between Kp and Kc',
            "Le Chatelier's Principle (Numericals not required)",
          ],
        },
      ],
    },
    {
      area: 'Inorganic Chemistry',
      totalHours: 30,
      units: [
        {
          unitNumber: 9,
          unitTitle: 'Chemistry of Non-metals',
          teachingHours: 22,
          topics: [
            'Hydrogen, Oxygen & Ozone: Atomic and nascent hydrogen, hydrogen isotopes & uses, hydrogen as fuel, heavy water',
            'Hydrogen, Oxygen & Ozone: Allotropes of oxygen, types of oxides (acidic, basic, neutral, amphoteric, peroxide, mixed)',
            'Hydrogen, Oxygen & Ozone: Applications of hydrogen peroxide',
            'Hydrogen, Oxygen & Ozone: Medical and industrial application of oxygen',
            'Hydrogen, Oxygen & Ozone: Ozone: Occurrence, preparation, structure, test, ozone layer depletion (causes, effects, control), uses',
            'Nitrogen: Inertness of nitrogen and active nitrogen',
            'Nitrogen: Chemical properties, applications, and harmful effects of ammonia',
            'Nitrogen: Oxy-acids of nitrogen (name and formula)',
            'Nitrogen: Chemical properties of nitric acid (acidic & oxidizing agent properties)',
            'Nitrogen: Ring test for nitrate ion',
            'Halogens: General characteristics of halogens',
            'Halogens: Comparative study on preparation, chemical properties (with water, alkali, ammonia, oxidizing/bleaching action), and uses of Cl2, Br2, I2',
            'Halogens: Tests for Cl2, Br2, and I2',
            'Halogens: Comparative study on haloacids (HCl, HBr, HI): preparation, properties (reducing strength, acidic nature, solubility), and uses',
            'Carbon: Allotropes of carbon including fullerenes (structure, properties, uses)',
            'Carbon: Properties and uses of carbon monoxide',
            'Phosphorus & Sulphur: Phosphorus: Allotropes (names), phosphine preparation, properties, and uses',
            'Phosphorus & Sulphur: Sulphur: Allotropes (names) and uses',
            'Phosphorus & Sulphur: Hydrogen sulphide: preparation (Kipp\'s apparatus), properties, and uses',
            'Phosphorus & Sulphur: Sulphur dioxide: properties and uses',
            'Phosphorus & Sulphur: Sulphuric acid: properties and uses',
            'Phosphorus & Sulphur: Sodium thiosulphate: formula and uses',
          ],
        },
        {
          unitNumber: 10,
          unitTitle: 'Chemistry of Metals',
          teachingHours: 5,
          topics: [
            'Metallurgical principles: metallurgy types, ores, gangue, flux, slag, alloy, amalgam',
            'General extraction principles: concentration, calcination, roasting, smelting, carbon reduction, thermite, electrochemical reduction',
            'Metal refining: poling and electro-refinement',
            "Alkali Metals: Sodium extraction via Down's process, NaOH properties/uses, Na2CO3 properties/uses",
            'Alkaline Earth Metals: Quick lime, bleaching powder, magnesia, plaster of Paris, Epsom salt formulas and uses; solubility trends of hydroxides/carbonates/sulphates; stability trends of carbonates/nitrates',
          ],
        },
        {
          unitNumber: 11,
          unitTitle: 'Bio-inorganic Chemistry',
          teachingHours: 3,
          topics: [
            'Introduction to Bio-inorganic Chemistry',
            'Micro and macro nutrients',
            'Importance of biological metal ions (Na, K, Mg, Ca, Fe, Cu, Zn, Ni, Co, Cr)',
            'Ion pumps (sodium-potassium and sodium-glucose pumps)',
            'Metal toxicity (iron, arsenic, mercury, lead, cadmium)',
          ],
        },
      ],
    },
    {
      area: 'Organic Chemistry',
      totalHours: 30,
      units: [
        {
          unitNumber: 12,
          unitTitle: 'Basic Concept of Organic Chemistry',
          teachingHours: 6,
          topics: [
            'Introduction to organic chemistry & organic compounds',
            'Reasons for separate study of organic compounds',
            'Tetra-covalency and catenation properties of carbon',
            'Classification of organic compounds',
            'Alkyl groups, functional groups, and homologous series',
            'Structural, contracted, and bond line structural formulas',
            'Cracking, reforming, gasoline quality, octane number, cetane number, gasoline additives',
          ],
        },
        {
          unitNumber: 13,
          unitTitle: 'Fundamental Principles of Organic Chemistry',
          teachingHours: 10,
          topics: [
            'IUPAC Nomenclature of organic compounds (up to 6 carbons)',
            'Qualitative analysis of organic compounds (Lassaigne\'s test for N, S, halogens)',
            'Isomerism: classification, structural isomerism (chain, position, functional, metamerism, tautomerism), stereoisomerism (geometrical cis/trans, optical d/l forms)',
            'Reaction Mechanism: Homolytic and heterolytic fission, electrophiles, nucleophiles, free radicals, Inductive effect (+I, -I), Resonance effect (+R, -R)',
          ],
        },
        {
          unitNumber: 14,
          unitTitle: 'Hydrocarbons',
          teachingHours: 8,
          topics: [
            'Saturated Hydrocarbons (Alkanes): Preparation (reduction, Wurtz reaction, decarboxylation, catalytic hydrogenation), substitution reactions, oxidation of ethane',
            'Unsaturated Hydrocarbons (Alkenes & Alkynes): Alkenes preparation (dehydration, dehydrohalogenation), addition reactions (Markovnikov\'s addition, peroxide effect); Alkynes preparation and addition/acidic reactions',
            'Tests of unsaturation: Bromine water test and Baeyer\'s test',
            'Comparative physical properties of alkanes, alkenes, and alkynes',
            "Kolbe's electrolysis methods",
          ],
        },
        {
          unitNumber: 15,
          unitTitle: 'Aromatic Hydrocarbons',
          teachingHours: 6,
          topics: [
            'Introduction and characteristics of aromatic compounds',
            "Huckel's rule of aromaticity",
            'Kekule structure of benzene',
            'Resonance and isomerism',
            'Preparation of benzene (decarboxylation of sodium benzoate, phenol, ethyne)',
            'Physical properties of benzene',
            'Chemical properties of benzene: Addition reactions, Electrophilic substitution reactions (nitration, sulphonation, halogenation, Friedel-Crafts alkylation/acylation), orientation of derivatives (o, m, p), combustion, and uses',
          ],
        },
      ],
    },
    {
      area: 'Applied Chemistry',
      totalHours: 15,
      units: [
        {
          unitNumber: 16,
          unitTitle: 'Fundamentals of Applied Chemistry',
          teachingHours: 4,
          topics: [
            'Chemical industry importance',
            'Stages in producing a new product',
            'Economics of production & cash flow cycle',
            'Running and designing a chemical plant',
            'Continuous vs batch processing',
            'Environmental impact of chemical industry',
          ],
        },
        {
          unitNumber: 17,
          unitTitle: 'Modern Chemical Manufactures',
          teachingHours: 11,
          topics: [
            "Ammonia manufacture by Haber's process",
            "Nitric acid manufacture by Ostwald's process",
            'Sulphuric acid manufacture by Contact process',
            'Sodium hydroxide manufacture by Diaphragm Cell',
            'Sodium carbonate manufacture by Solvay (ammonia-soda) process',
            'Chemical fertilizers: types and urea production flow-sheet diagram',
          ],
        },
      ],
    },
  ],
};

export default chemistrySyllabus;
